<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Bookmark;
use Doctrine\ORM\EntityRepository;

/**
 * BookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmarkRepository extends EntityRepository
{
    /**
     * Save entity.
     *
     * @param Bookmark $bookmark Bookmark entity
     */
    public function save(Bookmark $bookmark)
    {
        $this->_em->persist($bookmark);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param Bookmark $bookmark Bookmark entity
     */
    public function delete(Bookmark $bookmark)
    {
        $this->_em->remove($bookmark);
        $this->_em->flush();
    }
}
