<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Bookmark;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * BookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmarkRepository extends EntityRepository
{
    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll(), false));
        $paginator->setMaxPerPage(Bookmark::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

    /**
     * Query all Attributes.
     *
     * @return \Doctrine\ORM\Query
     */
    protected function queryAll()
    {
        $qb = $this->createQueryBuilder('b');
        $qb->select('b')
            ->orderBy('b.id', 'DESC');

        dump($qb->getQuery()->getResult());

        return $qb;
    }

    /**
     * Test of search.
     *
     * @return \Doctrine\ORM\Query
     */
    public function search($page)
    {
        $qb = $this->queryAll()->where('b.id > :id')
            ->setParameter(':id', 12);

        $paginator = new Pagerfanta(new DoctrineORMAdapter($qb, false));
        $paginator->setMaxPerPage(Bookmark::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;

    }

    /**
     * Save entity.
     *
     * @param Bookmark $bookmark Bookmark entity
     */
    public function save(Bookmark $bookmark)
    {
        $this->_em->persist($bookmark);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param Bookmark $bookmark Bookmark entity
     */
    public function delete(Bookmark $bookmark)
    {
        $this->_em->remove($bookmark);
        $this->_em->flush();
    }
}
