<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Bookmark;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * BookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmarkRepository extends EntityRepository
{
    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll(), false));
        $paginator->setMaxPerPage(Bookmark::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

    /**
     * Query all Attributes.
     *
     * @return \Doctrine\ORM\Query
     */
    protected function queryAll()
    {
        return $this->_em->createQuery('
            SELECT bookmark
            FROM AppBundle:Bookmark bookmark
        ');
    }

    /**
     * Save entity.
     *
     * @param Bookmark $bookmark Bookmark entity
     */
    public function save(Bookmark $bookmark)
    {
        $this->_em->persist($bookmark);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param Bookmark $bookmark Bookmark entity
     */
    public function delete(Bookmark $bookmark)
    {
        $this->_em->remove($bookmark);
        $this->_em->flush();
    }
}
